apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector: 
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
      - name: goserver
        image: "wmcruz/hello-go:v4.1"
        envFrom:
          - configMapRef:
              name: configmap-family

        volumeMounts:
            - mountPath: "/go/myfamily"
              name: config
      
      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
              - key: members
                path: family.txt