apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector: 
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
      - name: goserver
        image: "wmcruz/hello-go:v3"
        # FORMA Nº 3 E MAIS SIMPLES DE SE DECLARAR VARIÁVEIS DE AMBIENTE
        envFrom:
          - configMapRef:
              name: goserver-env
        # FORMA NUMERO 1 DE SE DECLARAR VARIÁVEIS DE AMBIENTE
        #env:
          #- name: NAME
          #  value: "Wellington"
          #- name: AGE
          #  value: "29"
        
        # FORMA NUMERO 2 DE SE DECLARAR VARIÁVEIS DE AMBIENTE 
          #- name: NAME
           # valueFrom:
           #   configMapKeyRef:
           #     key: NAME
           #     name: goserver-env
          #- name: AGE
          #  valueFrom:
          #    configMapKeyRef:
          #      key: AGE
          #      name: goserver-env