apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: goserver-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: goserver
    name: Deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 25